export const wagmiAbi = [
  {
    constant: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "recordId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "userAddress",
        type: "address",
      },
    ],
    name: "RecordAdded",
    payable: false,
    type: "event",
  },
  {
    constant: false,
    inputs: [
      {
        indexed: false,
        internalType: "string",
        name: "_species",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "_latitude",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "_longitude",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "_timeCaptured",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "_imageWalrusBlobId",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "_descriptionWalrusBlobId",
        type: "string",
      },
    ],
    name: "addRecord",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "getAllRecords",
    outputs: [
      {
        components: [
          { name: "species", type: "string" },
          { name: "latitude", type: "string" },
          { name: "longitude", type: "string" },
          { name: "timeCaptured", type: "string" },
          { name: "imageWalrusBlobId", type: "string" },
          { name: "descriptionWalrusBlobId", type: "string" },
          { name: "userAddress", type: "address" },
        ],
        internalType: "struct WildlifeSpottingRecords.SpottingRecord[]",
        name: "",
        type: "tuple[]",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_userAddress",
        type: "address",
      },
    ],
    name: "getAllUserRecords",
    outputs: [
      {
        components: [
          { name: "species", type: "string" },
          { name: "latitude", type: "string" },
          { name: "longitude", type: "string" },
          { name: "timeCaptured", type: "string" },
          { name: "imageWalrusBlobId", type: "string" },
          { name: "descriptionWalrusBlobId", type: "string" },
          { name: "userAddress", type: "address" },
        ],
        internalType: "struct WildlifeSpottingRecords.SpottingRecord[]",
        name: "",
        type: "tuple[]",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "_recordId",
        type: "uint256",
      },
    ],
    name: "getRecord",
    outputs: [
      {
        components: [
          { name: "species", type: "string" },
          { name: "latitude", type: "string" },
          { name: "longitude", type: "string" },
          { name: "timeCaptured", type: "string" },
          { name: "imageWalrusBlobId", type: "string" },
          { name: "descriptionWalrusBlobId", type: "string" },
          { name: "userAddress", type: "address" },
        ],
        internalType: "struct WildlifeSpottingRecords.SpottingRecord",
        name: "",
        type: "tuple",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_userAddress",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "_index",
        type: "uint256",
      },
    ],
    name: "getUserRecord",
    outputs: [
      {
        components: [
          { name: "species", type: "string" },
          { name: "latitude", type: "string" },
          { name: "longitude", type: "string" },
          { name: "timeCaptured", type: "string" },
          { name: "imageWalrusBlobId", type: "string" },
          { name: "descriptionWalrusBlobId", type: "string" },
          { name: "userAddress", type: "address" },
        ],
        internalType: "struct WildlifeSpottingRecords.SpottingRecord",
        name: "",
        type: "tuple",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "_userAddress",
        type: "address",
      },
    ],
    name: "getUserRecordCount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { indexed: false, internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "records",
    outputs: [
      { internalType: "string", name: "species", type: "string" },
      { internalType: "string", name: "latitude", type: "string" },
      { internalType: "string", name: "longitude", type: "string" },
      { internalType: "string", name: "timeCaptured", type: "string" },
      { internalType: "string", name: "imageWalrusBlobId", type: "string" },
      {
        internalType: "string",
        name: "descriptionWalrusBlobId",
        type: "string",
      },
      { internalType: "address", name: "userAddress", type: "address" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { indexed: false, internalType: "address", name: "", type: "address" },
      { indexed: false, internalType: "uint256", name: "", type: "uint256" },
    ],
    name: "userRecordIndices",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
] as const;
